Adding initial code and installing black, mypy, flake8, etc
frc1860/computer-vision pull request #1
Opened 2022-02-07 03:19 UTC by cl3t0

2022-02-08 00:32 UTC, Bertonebreno requested changes

2022-02-08 00:32 UTC, Bertonebreno commented on Makefile
> +
Where is the `make run`?

2022-02-08 00:32 UTC, Bertonebreno commented on pyproject.toml
> +authors = ["Pedro Cleto <cl3t0.sh@gmail.com>"]
Where is me? 👀

2022-02-08 00:32 UTC, Bertonebreno commented on setup.cfg
> +max-complexity = 17
Lower this to 10

2022-02-08 02:06 UTC, cl3t0 commented on Makefile
> +
I will create it after the separation of camera logic and roboRIO communication.

2022-02-08 02:11 UTC, cl3t0 commented on pyproject.toml
> +authors = ["Pedro Cleto <cl3t0.sh@gmail.com>"]
Added.

2022-02-08 03:32 UTC, cl3t0 commented on setup.cfg
> +max-complexity = 17
I lowered it to 11.

2022-02-17 03:17 UTC, Bertonebreno approved these changes

2022-02-17 03:18 UTC, merged